export const DOUBLE_TAP_TIMEOUT = 300;
export const DOUBLE_TAP_THRESHOLD = 20;
export const DOUBLE_TAP_ZOOM = 0.2;
export const CONTAINER_WIDTH_CHANGE_RATE = 500;
export const RESIZE_UPDATE_THRESHOLD = 30;
