#!/bin/sh
# expects cwd to be subpackage root
if [ "$1" = "--ssr-preview" ]
then
  SSR=true start-storybook -p 3000 --ci --preview-url=/ssr-iframe --config-dir ../../.storybook
else
  start-storybook -p 3000 --ci --config-dir ../../.storybook
fi

