name: Check
on: push
jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: npm i -g npm@7 --registry=https://registry.npmjs.org
    - run: npm run ci
    - run: npm run check
  deploy-preview:
    name: Build & Deploy preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: npm i -g npm@7 --registry=https://registry.npmjs.org
      - run: npm run ci
      - run: npm run build:preview
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: .
