name: Check
on: push
jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: npm i -g npm@7 --registry=https://registry.npmjs.org
    - run: yarn run build
    - run: yarn install --frozen-lockfile
    - run: npm run check

