name: Check
on: push
jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
    # Checkout the Repo
    - uses: actions/checkout@v4

    # Install Node 18
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # Install dependencies
    - run: yarn install --frozen-lockfile

    # Run tests
    - run: yarn run check

