name: Build & Deploy preview
on:
  push:
    branches:
      - master
jobs:
  deploy-preview:
    name: Build & Deploy preview
    runs-on: ubuntu-latest
    steps:
      # Checkout the Repo
      - uses: actions/checkout@v3

      # Install Node 16
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Install dependencies
      - run: yarn install --frozen-lockfile

      # Build preview
      - run: yarn run build:preview

      # Deploy to github pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .
