name: Build & Deploy preview
on:
  push:
    branches:
      - master
      - fix-gh-actions
jobs:
  deploy-preview:
    name: Build & Deploy preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: yarn install --frozen-lockfile
      - run: yarn run tryBuild:preview
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: .
