const GENDER_FEMALE = 0;
const GENDER_MALE = 1;

const ADS_GENDER_FEMALE = 'FEMALE';
const ADS_GENDER_MALE = 'MALE';

export const ADS_GENDER_MAP = {
  [GENDER_FEMALE]: ADS_GENDER_FEMALE,
  [GENDER_MALE]: ADS_GENDER_MALE,
};
